import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Session from "@/components/Session";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <Session session={session}>
        <Header />
        {children}
        </Session>
      </body>
    </html>
  );
}
